-- Use Case 30: Isolation Levels

-- Session 1
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM covid_cases WHERE Country='India';
COMMIT;

-- Session 2
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
UPDATE covid_cases
SET Confirmed = Confirmed + 100
WHERE Country='India';
COMMIT;

-- Serializable Example
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
